# Generated by Django 5.2.17 on 2026-09-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traspaso",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("V", "Vigente"), ("A", "Anulado")],
                        default="V",
                        max_length=1,
                    ),
                ),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empleado",
                    ),
                ),
                (
                    "tienda_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traspasos_recibidos",
                        to="core.tienda",
                    ),
                ),
                (
                    "tienda_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traspasos_enviados",
                        to="core.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traspaso",
                "verbose_name_plural": "Traspasos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="TraspasoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
                (
                    "traspaso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="inventario.traspaso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de traspaso",
                "verbose_name_plural": "Detalle de traspasos",
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("existencia", models.IntegerField(default=0)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="productos.producto",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="core.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventario",
                "ordering": ["tienda", "producto"],
                "unique_together": {("tienda", "producto")},
            },
        ),
    ]
