# Generated by Django 5.2.17 on 2026-09-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_snapshotdemo"),
        ("inventario", "0001_initial"),
        ("productos", "0002_producto_stock_minimo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_lote", models.CharField(blank=True, max_length=50)),
                ("cantidad", models.PositiveIntegerField(default=0)),
                ("fecha_vencimiento", models.DateField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="productos.producto",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="core.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["fecha_vencimiento"],
            },
        ),
    ]
