# Generated by Django 5.2.17 on 2026-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_empleado_tipo_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personalizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paleta",
                    models.CharField(
                        choices=[
                            ("azul", "Azul oscuro (predeterminado)"),
                            ("verde", "Verde esmeralda"),
                            ("morado", "Morado"),
                            ("gris", "Gris / Negro"),
                            ("vino", "Vino / Rojo oscuro"),
                        ],
                        default="azul",
                        max_length=20,
                    ),
                ),
                ("foto_fondo", models.BinaryField(blank=True, null=True)),
                ("foto_fondo_tipo", models.CharField(blank=True, max_length=50)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personalización",
                "verbose_name_plural": "Personalización",
            },
        ),
    ]
