# Generated by Django 5.2.17 on 2026-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_personalizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalizacion",
            name="tipo_sistema",
            field=models.CharField(
                choices=[
                    ("ropa", "Tienda de Ropa"),
                    ("libreria", "Librería"),
                    ("farmacia", "Farmacia"),
                    ("abarroteria", "Abarrotería"),
                ],
                default="ropa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personalizacion",
            name="paleta",
            field=models.CharField(
                choices=[
                    ("azul", "Azul oscuro (predeterminado)"),
                    ("verde", "Verde esmeralda"),
                    ("morado", "Morado"),
                    ("gris", "Gris / Negro"),
                    ("vino", "Vino / Rojo oscuro"),
                    ("blanco", "Blanco"),
                ],
                default="azul",
                max_length=20,
            ),
        ),
    ]
