# Generated by Django 5.2.17 on 2026-09-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto en quetzales que se resta del subtotal antes del total.",
                max_digits=12,
            ),
        ),
    ]
