# Generated by Django 5.2.17 on 2026-09-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("V", "Venta"), ("D", "Devolución")],
                        default="V",
                        max_length=1,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("V", "Vigente"), ("A", "Anulada")],
                        default="V",
                        max_length=1,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("comentario_anulacion", models.CharField(blank=True, max_length=255)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empleado",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="core.tienda",
                    ),
                ),
                (
                    "venta_original",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es una devolución, referencia a la venta original.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devoluciones",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VentaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de venta",
                "verbose_name_plural": "Detalle de ventas",
            },
        ),
    ]
