# Generated by Django 5.2.17 on 2026-09-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0005_snapshotdemo"),
        ("productos", "0002_producto_stock_minimo"),
        ("ventas", "0002_venta_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="forma_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                    ("credito", "Crédito"),
                ],
                default="efectivo",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AbonoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono de venta",
                "verbose_name_plural": "Abonos de venta",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("desde", models.DateTimeField()),
                ("hasta", models.DateTimeField(auto_now_add=True)),
                (
                    "total_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tarjeta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_transferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cantidad_ventas", models.PositiveIntegerField(default=0)),
                (
                    "efectivo_contado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empleado",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cierres_caja",
                        to="core.tienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de caja",
                "verbose_name_plural": "Cierres de caja",
                "ordering": ["-hasta"],
            },
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("A", "Activa"),
                            ("C", "Convertida a venta"),
                            ("X", "Cancelada"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizaciones",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empleado",
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="core.tienda",
                    ),
                ),
                (
                    "venta_generada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizacion_origen",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CotizacionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="ventas.cotizacion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de cotización",
                "verbose_name_plural": "Detalle de cotizaciones",
            },
        ),
    ]
