# Generated by Django 5.2.17 on 2026-09-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="tipo_usuario",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("empleado", "Empleado")],
                default="empleado",
                max_length=10,
            ),
        ),
    ]
