# Generated by Django 5.2.17 on 2026-09-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_personalizacion_tipo_sistema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotDemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datos", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(blank=True, null=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Foto de datos de demo",
                "verbose_name_plural": "Foto de datos de demo",
            },
        ),
    ]
