# Generated by Django 5.2.17 on 2026-09-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_minimo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Existencia mínima deseada. En 0, no se muestran alertas de stock bajo para este producto.",
            ),
        ),
    ]
