# Generated by Django 5.2.17 on 2026-09-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "nit_documento",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="NIT / Documento"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ClienteDireccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                ("referencia", models.CharField(blank=True, max_length=150)),
                ("principal", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección de cliente",
                "verbose_name_plural": "Direcciones de cliente",
            },
        ),
        migrations.CreateModel(
            name="ClienteTelefono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(max_length=50)),
                (
                    "etiqueta",
                    models.CharField(
                        blank=True,
                        help_text="Ej: celular, casa, trabajo",
                        max_length=50,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telefonos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teléfono de cliente",
                "verbose_name_plural": "Teléfonos de cliente",
            },
        ),
    ]
