# Generated by Django 5.2.17 on 2026-09-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="forma_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                    ("credito", "Crédito"),
                ],
                default="efectivo",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AbonoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.CharField(blank=True, max_length=255)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="compras.compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono de compra",
                "verbose_name_plural": "Abonos de compra",
                "ordering": ["-fecha"],
            },
        ),
    ]
